### PR TITLE
Make getResourceTranslation get actual translations.

### PR DESCRIPTION
**Pull request by freaktechnik**

### CODE REVIEW

**Comment by freaktechnik** [comment]
Sorry about the removal of all trailing whitespace. I can resubmit without that, if you'd prefer that.

**Comment by alexanderwallin** [comment]
Hey @freaktechnik.

Thanks for submitting the PR. I just checked my local repo, and the public master way behind as I have not pushed changes for a while. The functionality in your PR is already implemented, except for the `mode` argument.

I'll close this and push my changes. Sorry about the inconvenience!

**Comment by freaktechnik** [comment]
Thanks, that'd explain why it somehow magically worked against all odds, so I can remove my workaround of using _send.

**Comment by alexanderwallin** [comment]
Yeah, I published it to npm but not to GitHub. :/

**Pull request closed without merging**
